services:
  - type: web
    name: trifair
    runtime: docker
    plan: free
    healthCheckPath: /login
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: https://trifair.onrender.com
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.lkmmudpfcxbykwdpsqvy.supabase.co
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: "TriFair2026!StrongPass"
      - key: SESSION_DRIVER
        value: cookie
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: SESSION_SAME_SITE
        value: none
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
